apiVersion: apps/v1
kind: Deployment
metadata:
  name: bfdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bfdb
  template:
    metadata:
      labels:
        app: bfdb
    spec:
      containers:
      - image: okteto.dev/bfdb:latest
        name: bfdb
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d079d004-02db-450a-b113-a09593f660a9"
        - name: Vless_Path
          value: "/vldfg555"
        - name: Vmess_UUID
          value: "d079d004-02db-450a-b113-a09593f660a9"
        - name: Vmess_Path
          value: "/vm6gd66"
        - name: Share_Path
          value: "/v2link"
